[package]
name = "xtask"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.0.10", features = ["derive"] }
lumeo-api-client = { path = "../lumeo_api_client" }
serde_json = "1.0.68"
